apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-trackpackers
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  # - host: <Host>
  - http:
      paths:
      - pathType: Prefix
        path: /contentwriter(/|$)(.*)
        backend:
          service:
            name: contentwriter-service
            port: 
              number: 80